### ISSUE TITLE
Issue at retrieving verification code

### ISSUE THREAD

**Issue by SgtSobieski** [Memessidy/protonmail-generator#7]
Error log:
![image](https://github.com/Memessidy/protonmail-generator/assets/125480018/07ea84da-db3a-467e-80fb-0d2ff0da2569)

**Comment by Memessidy** [comment]
Updated. Try a new version please))

**Comment by Memessidy** [comment]
Updated, please try a new verion))

**Comment by SgtSobieski** [comment]
Thanks - works!
